### ISSUE TITLE
What is the recommanded way of testing a cppcms::application?

### ISSUE THREAD

**Issue by ArthurSonzogni** [artyom-beilis/cppcms#10]
Hello,

I have a REST server implemented as a cppcms::application.
I would like to add some tests for it. I don't really want to do a network request, but only set the application context, call the main method and check the response. Is it possible? What would you recommand?

What I have tried so far:
1) Create a new cppcms::service.
2) Create a new cppcms::application <-- my REST server
3) Call application.main("url_path")
4) Check application.response()

Between  2) and 3) I probably need to call cppcms::application::assign_context(<context>). But there is no way to create one as its constructor depends on impl::cgi::connection.

**Comment by artyom-beilis** [comment]
First of all such a question should be addressed to the cppcms users mailing list. 

Currently it is not possible to create a request without using private API. I do it in some unit tests but mostly I create simple requests from python

**Comment by artyom-beilis** [comment]
Also I  think having such an option in public API  for unit testing is good idea.

**Comment by ArthurSonzogni** [comment]
Sorry for posting here. The [help wanted] label made me think I had to do it here.

I would be very interested having such an option in public API for unit testing. It is easier for me to test my code from inside. So, you think there would be no major problems implement this. I will take a look at cppcms implementation, looking if I could do something maybe.

**Comment by artyom-beilis** [comment]
Closed as irrelevant
