### ISSUE TITLE
cppcms::b64url compatibility

### ISSUE THREAD

**Issue by masaoliou** [artyom-beilis/cppcms#102]
I have tested on https://dogmamix.com/MimeHeadersDecoder and https://www.base64encode.org and have found that cppcms::b64url::encode() seems to be incompatible with https://datatracker.ietf.org/doc/html/rfc2047.txt

This [implementation](https://gist.github.com/tomykaira/f0fd86b6c73063283afe550bc5d77594) works as expected.

Any idea?

**Comment by artyom-beilis** [comment]
Can you please be more specific. What exactly does not compatible?

Can you show example if what b64url creates and what do you expect?

**Comment by masaoliou** [comment]
````
#include <cppcms/base64.h>
#include <sstream>
#include <iostream>

int main()
{
	const std::string s("This is John Smith.");
	std::ostringstream os;
	cppcms::b64url::encode(reinterpret_cast<const unsigned char*>(s.c_str()),reinterpret_cast<const unsigned char*>(s.c_str())+s.size(),os);
	std::cout << os.str() << std::endl; //VGhpcyBpcyBKb2huIFNtaXRoLg
	std::cout << "=?utf-8?B?" << os.str() << "?=" << std::endl; //=?utf-8?B?VGhpcyBpcyBKb2huIFNtaXRoLg?=
}
````
[This web page](https://dogmamix.com/MimeHeadersDecoder) can't decode the last string `=?utf-8?B?VGhpcyBpcyBKb2huIFNtaXRoLg?=` following "Subject: ".

The following shell command

`echo -ne "This is John Smith." | base64`

gives the following string:

`VGhpcyBpcyBKb2huIFNtaXRoLg==`

The [aforementioned web page](https://dogmamix.com/MimeHeadersDecoder) properly decodes the following string after "Subject: ":

`=?utf-8?B?VGhpcyBpcyBKb2huIFNtaXRoLg==?=`

**Comment by artyom-beilis** [comment]
I explain, there is difference between base64 and base64url

https://en.wikipedia.org/wiki/Base64#Variants_summary_table

Short summary:

- Base 64 uses `+` and `/` characters while base64url uses `-` and `_`
- Base64url does not require padding with `=` and does not require new lines

You are confusing two very similar but different encodings - the code you linked to is actually base64 and not base64url.
