### ISSUE TITLE
Synchronous applications being deleted during heavy load

### ISSUE THREAD

**Issue by GamerSg** [artyom-beilis/cppcms#20]
During heavy loads (ie DDOS, brute force password attempts), it is common to see constructors and destructors of my application being called rapidly. 

This has the side effect of abruptly terminating existing requests which are still running.

I've looked at the application_pool.cpp file and the policies seem to imply that delete app should never be called?

I am using cppcms 1.04

**Comment by artyom-beilis** [comment]
It is something that should be addressed in CppCMS >= 1.1.0

http://cppcms.com/wikipp/en/page/cppcms_1_2_pool_api

I suggest to upgrade to latest branch

**Comment by artyom-beilis** [comment]
closing due to lack of feedback
