### ISSUE TITLE
suggestion: add move operations for cppcms::json::value

### ISSUE THREAD

**Issue by mashomee** [artyom-beilis/cppcms#25]
Hi，thank you for your amazing library！

We have been using cppcms framework for a restful server lately。
As it is very often for us to dynamically generate JSON object，json::value generation speed is very important. We have add move constructor and move assignment operator for json::value, turns out it speed up about 30-60% in a large JSON object generation.
So, why not add the move operations when the compiler have move operation support?

Thank you again for your brilliant library!

**Comment by artyom-beilis** [comment]
In general it is valid and very important suggestion. However CppCMS currently does not expose or provides C++11 interfaces. It is on the roadmap but not at this point.

In general there are lots of improvements that can be done by moving to C++11 and it is relevant for large parts of CppCMS - not json only.

At this point I recomment to use value.swap() for moving values.

**Comment by mashomee** [comment]
I see, waiting for it.
Thanks.
