### ISSUE TITLE
Twice rendering in main?

### ISSUE THREAD

**Issue by HadesD** [artyom-beilis/cppcms#3]
I 've test add **#include <stdio.h>** to hello.cpp file and do a printf and this is result:

Code:
```c++
void hello::main(std::string /*url*/)
{
  response().out() <<
  "<html>\n"
  "<body>\n"
  "  <h1>Hello World</h1>\n"
  "</body>\n"
  "</html>\n";
  printf ("Characters: %c %c \n", 'a', 65);
}
```
Then i open browser once, but result is print twice:
Result:
```
Characters: a A 
Characters: a A
```
Is it run twice in code?

**Comment by botanegg** [comment]
random reason: You browser can try load yousite/favicon.ico
Inspect you developer console

**Comment by artyom-beilis** [comment]
You need to check your URLs...
