### ISSUE TITLE
Request method PATCH does can not load(context()) to form elements

### ISSUE THREAD

**Issue by HadesD** [artyom-beilis/cppcms#30]
I'm trying to write Rest APT, that uses PATCH and more another method.
But it can not `load(context())` to the `cppcms::form`. When I change Route form PATCH -> POST, it working successfully.

After read documentations, I heard that now `load(context())` only extract data from `POST/GET`

What should I do to implement full Rest API style?

**Comment by artyom-beilis** [comment]
In general if you want to use `application/x-www-form-urlencoded` with forms. If you write RESTful service you usually send entire object instead encoded to some format.
