### ISSUE TITLE
whether the json object is iterable ?

### ISSUE THREAD

**Issue by pingsoli** [artyom-beilis/cppcms#31]
```
cppcms::json::value my_object;

my_object["name"]    = "Moshe";
my_object["salary"]  = 1000.0;
my_object["retired"] = false;

for (/* iterate the json object */)
{
  std::cout << "key: " << it.key() << " value: " << it.value() <<std::endl;
}

```
I just want to get the output like this, do you have any idea to do this ?
```
key: name value: Moshe
key: salary value: 1000.0
key: retired value: false
```
I'll apperciate your reply.

**Comment by artyom-beilis** [comment]
Yes they are iterable: object is std::map and array is std::vector

http://cppcms.com/cppcms_ref/latest/namespacecppcms_1_1json.html#a4849268540ccdea30cfa408d6706d0c9

**Comment by pingsoli** [comment]
@artyom-beilis Thanks, I should read the doc carefully. sorry to disturb you.
