### ISSUE TITLE
`cache_frontend_test` build fails on `-DDISABLE_GZIP=ON`

### ISSUE THREAD

**Issue by luav** [artyom-beilis/cppcms#36]
```sh
cppcms/build$ cmake -DDISABLE_SCGI=ON -DDISABLE_GZIP=ON ..
$ make
```
yields the following error:
```sh
...
[ 28%] Linking CXX shared library libloadable_storage.so
[ 28%] Built target loadable_storage
[ 28%] Linking CXX executable cache_frontend_test
libcppcms.so.1.2.0: undefined reference to `crc32'
collect2: error: ld returned 1 exit status
CMakeFiles/cache_frontend_test.dir/build.make:103: recipe for target 'cache_frontend_test' failed
make[2]: *** [cache_frontend_test] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/cache_frontend_test.dir/all' failed
make[1]: *** [CMakeFiles/cache_frontend_test.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
`crc32()` is defined in `libz`, which makes sense to replace with the statically linked hashing.  
For example, [xxHash](https://cyan4973.github.io/xxHash/) could be statically linked (it has BSD license, which is almost the same as MIT) to avoid dependency of libz (crc32) producing fast cross-platform hashing of significantly better quality than crc32.

**Comment by artyom-beilis** [comment]
> `crc32()` is defined in libz, which makes sense to replace with the statically linked hashing.

libz is widely available and important part of CppCMS so I don't see reason why not to deploy with one - since it is small universally available library. 

> For example, xxHash could be statically linked (it has BSD license, which is almost the same as MIT) to avoid dependency of libz (crc32) producing fast cross-platform hashing of significantly better quality than crc32.

Replacing crc32 with other hash will cause all existing sessions to be invalid upon upgrade so it is bad idea
