### ISSUE TITLE
Multi core async application?

### ISSUE THREAD

**Issue by shivshankardayal** [artyom-beilis/cppcms#39]
How to write a multi core async appplication? Can you please give an example?

**Comment by artyom-beilis** [comment]
It is on the road-map - implementation of multiple event loops. Currently all async app run in single thread, you can post some heavy jobs to thread pool and wait for the response in asynchronous way,

**Comment by shivshankardayal** [comment]
Why cannot we model it using reactor pattern? One event loop and then rest of worker cores much like Seastar framework?

**Comment by artyom-beilis** [comment]
Currently CppCMS uses many worker cores for synchronus apps - while single even loop distributes the job between workers. 

Async apps live in the event loop and should not do heavy jobs

**Comment by shivshankardayal** [comment]
Closing it.
