### ISSUE TITLE
Error in doc for building in debain

### ISSUE THREAD

**Issue by pcouderc12** [artyom-beilis/cppcms#55]
After :
cmake ..
I get:  
No CMAKE_CXX_COMPILER could be found. 

I am trying to install g++. 
Anyway it is highly discouraging to get a failure when building a new tool.
Please add g++ in the doc if it is the good solution page: 
http://cppcms.com/wikipp/en/page/cppcms_1x_build

**Comment by artyom-beilis** [comment]
It is like basic things - you need to have compiler - in general build-essential is the package for Debian/Ubuntu
