### ISSUE TITLE
how to change the site configuration (config.js) from http to https

### ISSUE THREAD

**Issue by Hethsron** [artyom-beilis/cppcms#57]
@artyom-beilis how to change the site configuration (config.js) from http to https?

**Comment by masaoliou** [comment]
CppCMS is scheme agnostic. You want to configure HTTP server instead.

**Comment by Hethsron** [comment]
@masaoliou yes I want to configure http server instead.

**Comment by Hethsron** [comment]
And redirect all my http requests to https

**Comment by Hethsron** [comment]
I thought it was enough to add certificates in the config.js file

**Comment by Hethsron** [comment]
But I didn't find anything about it in the doc of CppCMS

**Comment by Hethsron** [comment]
@masaoliou So if you have an idea to solve my problem I am ready to know it beyond to find myself

**Comment by idkCpp** [comment]
You need a reverse proxy in front of CppCMS. Like Apache. 

This link will help you configuring Apache for HTTPS redirection:
https://stackoverflow.com/questions/16200501/http-to-https-apache-redirection

And this link will help you integrate your CppCMS App with Apache:
http://cppcms.com/wikipp/en/page/cppcms_1x_tut_web_server_config#Apache..FastCGI

**Comment by artyom-beilis** [comment]
http is not supported by CppCMS yet. So as @idkCpp said, you need to use any kind of HTTPs server as frontend like apache, nginx, lighttpd  and connect it via http/fastcgi/scgi protocol

The https support is on the roadmap: http://cppcms.com/wikipp/en/page/cppcms_1x_tasks

**Comment by Hethsron** [comment]
Thanks for this advice @idkCpp  @artyom-beilis
