### ISSUE TITLE
filter_test fails in Debian 8 BeagleBone

### ISSUE THREAD

**Issue by fquindos** [artyom-beilis/cppcms#7]
However it works in Debian 8 x64 (both updated the same day). It's the only test that fails.

**From log:**
19/104 Test: filter_test
Command: "/mnt/cppcms_git/build/filter_test" "-c" "/mnt/cppcms_git/tests/filter_test.js" "--test-exec=/usr/bin/python2 /mnt
/cppcms_git/tests/filter_test.py"
Directory: /mnt/cppcms_git/build
"filter_test" start time: Jul 03 16:08 UTC
Output:
----------------------------------------------------------
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
GET /upload/no_content
Got {'status': 200, 'no_content': 1, 'is_html': False} 
POST /upload?l_1=10&f_1=a&l_2=20&f_2=t
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 0, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=10&f_1=a&l_2=20&f_2=t&chunks=5
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 9, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=10000&f_1=a&l_2=20000&f_2=t
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 3, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=0&setbuf=10&at=1
Got {'status': 501, 'content': '<html>\r\n<body>\r\n<h1>501 Not Implemented</h1>\r\n</body>\r\n</html>\r\n', 'is_html': True} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=1&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=2&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=3&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=0&setbuf=10&at=1
Got {'status': 502, 'content': '<html>\r\n<body>\r\n<h1>502 Bad Gateway</h1>\r\n</body>\r\n</html>\r\n', 'is_html': True} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=1&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=2&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=3&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_upload_progress&how=0&setbuf=10&at=1
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 5, 'on_new_file': 1, 'on_data_ready': 1, 'post': 0, 'total': 1, 'files': 1} 
Traceback (most recent call last):
  File "/mnt/cppcms_git/tests/filter_test.py", line 262, in <module>
    test_upload()
  File "/mnt/cppcms_git/tests/filter_test.py", line 180, in test_upload
    test(r['status']==code)
  File "/mnt/cppcms_git/tests/filter_test.py", line 16, in test
    raise RuntimeError("Failed")
RuntimeError: Failed
FAILED
<end of output>
Test time =   3.48 sec
----------------------------------------------------------

**From manual run:**
# /mnt/cppcms_git/build/filter_test -c /mnt/cppcms_git/tests/filter_test.js --test-exec="/usr/bin/python2 /mnt/cppcms_git/tests/filter_test.py"
GET /upload/no_content
Got {'status': 200, 'no_content': 1, 'is_html': False} 
POST /upload?l_1=10&f_1=a&l_2=20&f_2=t
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 0, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=10&f_1=a&l_2=20&f_2=t&chunks=5
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 9, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=10000&f_1=a&l_2=20000&f_2=t
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 3, 'on_new_file': 2, 'on_data_ready': 2, 'post': 0, 'total': 2, 'files': 2} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=0&setbuf=10&at=1
Got {'status': 501, 'content': '<html>\r\n<body>\r\n<h1>501 Not Implemented</h1>\r\n</body>\r\n</html>\r\n', 'is_html': True} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=1&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=2&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_headers_ready&how=3&setbuf=10&at=1
Got {'status': 501, 'at': 'on_headers_ready', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=0&setbuf=10&at=1
Got {'status': 502, 'content': '<html>\r\n<body>\r\n<h1>502 Bad Gateway</h1>\r\n</body>\r\n</html>\r\n', 'is_html': True} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=1&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=2&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_new_file&how=3&setbuf=10&at=1
Got {'status': 502, 'at': 'on_new_file', 'is_html': False} 
POST /upload?l_1=50&f_1=a&abort=on_upload_progress&how=0&setbuf=10&at=1
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
FAIL: size_t(input_file.size()) << ref.size() in line: 115
Got {'status': 200, 'on_end_of_content': 1, 'is_html': False, 'on_upload_progress': 5, 'on_new_file': 1, 'on_data_ready': 1, 'post': 0, 'total': 1, 'files': 1} 
Traceback (most recent call last):
  File "/mnt/cppcms_git/tests/filter_test.py", line 262, in <module>
    test_upload()
  File "/mnt/cppcms_git/tests/filter_test.py", line 180, in test_upload
    test(r['status']==code)
  File "/mnt/cppcms_git/tests/filter_test.py", line 16, in test
    raise RuntimeError("Failed")
RuntimeError: Failed
FAILED

**Environment:**

# cat /etc/issue
Debian GNU/Linux 8 \n \l

BeagleBoard.org Debian Image 2016-12-09

Support/FAQ: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian

default username:password is [debian:temppwd]

The IP Address for eth0 is: 192.168.3.104
The IP Address for usb0 is: 192.168.7.2

# uname -a
Linux bbb-0 4.4.36-ti-r72 #1 SMP Wed Dec 7 22:29:53 UTC 2016 armv7l GNU/Linux

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by artyom-beilis** [comment]
Does it happen consistently? Can you rerun this test only several times:

    ctest -R filter_test

**Comment by fquindos** [comment]
Yes, I've tested it 10 times and got 10 fails.

Best regards,
Francisco Díaz

-----Original Message-----

**Comment by artyom-beilis** [comment]
Hello,

Thanks for the report, I only now noticed it was on ARM platform.

Can you check if this changeset fixes the issue: https://github.com/artyom-beilis/cppcms/commit/e8dffc58bb46e4172cf08fb4e5b8f46e41b6eb5e

You can just pull latest master to get one.

Also can you give me an output of the following program on ARM:


    #include <stdio.h>
    int main()
    {
        for(size_t v=0;v<65;v++) {
            size_t v2=1;
            v2 <<= v;
            printf("%2lu %lu\n",v,v2);
        }
    }

**Comment by fquindos** [comment]
Te program output follows. It's a 32 bit machine, as you can see. I'll try the new version and report the results sa soon as possible.

 0 1
 1 2
 2 4
 3 8
 4 16
 5 32
 6 64
 7 128
 8 256
 9 512
10 1024
11 2048
12 4096
13 8192
14 16384
15 32768
16 65536
17 131072
18 262144
19 524288
20 1048576
21 2097152
22 4194304
23 8388608
24 16777216
25 33554432
26 67108864
27 134217728
28 268435456
29 536870912
30 1073741824
31 2147483648
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 0
44 0
45 0
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
54 0
55 0
56 0
57 0
58 0
59 0
60 0
61 0
62 0
63 0
64 0


-----Original Message-----

**Comment by artyom-beilis** [comment]
Excellent, it confirms the problem I had seen. Please report me one you get to test it

**Comment by fquindos** [comment]
All tests ok! Thanks for the good job!

Test project /mnt/cppcms_git/build Start 1: base64_test 1/104 Test #1: base64_test ............................. Passed 1.98 sec Start 2: todec_test 2/104 Test #2: todec_test .............................. Passed 0.03 sec Start 3: response_test 3/104 Test #3: response_test ........................... Passed 0.25 sec Start 4: encryptor_test 4/104 Test #4: encryptor_test .......................... Passed 0.10 sec Start 5: storage_test 5/104 Test #5: storage_test ............................ Passed 0.05 sec Start 6: json_test 6/104 Test #6: json_test ............................... Passed 0.03 sec Start 7: hash_map_test 7/104 Test #7: hash_map_test ........................... Passed 0.04 sec Start 8: multipart_parser_test 8/104 Test #8: multipart_parser_test ................... Passed 4.25 sec Start 9: content_type_parser_test 9/104 Test #9: content_type_parser_test ................ Passed 0.06 sec Start 10: serialization_test 10/104 Test #10: serialization_test ...................... Passed 0.06 sec Start 11: xss_test 11/104 Test #11: xss_test ................................ Passed 0.10 sec Start 12: rewrite_test 12/104 Test #12: rewrite_test ............................ Passed 0.06 sec Start 13: url_mapper_test 13/104 Test #13: url_mapper_test ......................... Passed 0.41 sec Start 14: copy_filter_test 14/104 Test #14: copy_filter_test ........................ Passed 0.06 sec Start 15: mount_point_test 15/104 Test #15: mount_point_test ........................ Passed 0.06 sec Start 16: file_buffer_test 16/104 Test #16: file_buffer_test ........................ Passed 94.46 sec Start 17: status_test 17/104 Test #17: status_test ............................. Passed 1.06 sec Start 18: pool_test 18/104 Test #18: pool_test ............................... Passed 12.34 sec Start 19: filter_test 19/104 Test #19: filter_test ............................. Passed 12.50 sec Start 20: async_status_test 20/104 Test #20: async_status_test ....................... Passed 2.21 sec Start 21: form_test 21/104 Test #21: form_test ............................... Passed 2.44 sec Start 22: cookie_test 22/104 Test #22: cookie_test ............................. Passed 1.13 sec Start 23: internal_forwarder_test 23/104 Test #23: internal_forwarder_test ................. Passed 1.20 sec Start 24: forwarder_test 24/104 Test #24: forwarder_test .......................... Passed 1.15 sec Start 25: jsonrpc_test 25/104 Test #25: jsonrpc_test ............................ Passed 1.21 sec Start 26: http_timeouts_test_read 26/104 Test #26: http_timeouts_test_read ................. Passed 35.44 sec Start 27: http_timeouts_test_write 27/104 Test #27: http_timeouts_test_write ................ Passed 82.53 sec Start 28: file_server_test 28/104 Test #28: file_server_test ........................ Passed 1.02 sec Start 29: file_server_test_no_links 29/104 Test #29: file_server_test_no_links ............... Passed 0.94 sec Start 30: file_server_with_listing_test 30/104 Test #30: file_server_with_listing_test ........... Passed 0.96 sec Start 31: file_server_test_async 31/104 Test #31: file_server_test_async .................. Passed 0.64 sec Start 32: file_server_test_no_links_async 32/104 Test #32: file_server_test_no_links_async ......... Passed 0.65 sec Start 33: file_server_with_listing_test_async 33/104 Test #33: file_server_with_listing_test_async ..... Passed 0.48 sec Start 34: disco_test_http 34/104 Test #34: disco_test_http ......................... Passed 1.93 sec Start 35: disco_test_fastcgi_tcp 35/104 Test #35: disco_test_fastcgi_tcp .................. Passed 2.05 sec Start 36: disco_test_scgi_tcp 36/104 Test #36: disco_test_scgi_tcp ..................... Passed 2.05 sec Start 37: secure_post_test 37/104 Test #37: secure_post_test ........................ Passed 1.26 sec Start 38: disco_test_fastcgi_unix 38/104 Test #38: disco_test_fastcgi_unix ................. Passed 2.01 sec Start 39: disco_test_scgi_unix 39/104 Test #39: disco_test_scgi_unix .................... Passed 2.02 sec Start 40: gzip_test 40/104 Test #40: gzip_test ............................... Passed 1.87 sec Start 41: cppcms_service_test 41/104 Test #41: cppcms_service_test ..................... Passed 10.35 sec Start 42: external_session_test 42/104 Test #42: external_session_test ................... Passed 0.12 sec Start 43: session_interface_test_client_renew 43/104 Test #43: session_interface_test_client_renew ..... Passed 9.55 sec Start 44: session_interface_test_client_browser 44/104 Test #44: session_interface_test_client_browser ... Passed 9.71 sec Start 45: session_interface_test_client_fixed 45/104 Test #45: session_interface_test_client_fixed ..... Passed 9.71 sec Start 46: session_interface_test_server_renew 46/104 Test #46: session_interface_test_server_renew ..... Passed 9.78 sec Start 47: session_interface_test_server_browser 47/104 Test #47: session_interface_test_server_browser ... Passed 9.52 sec Start 48: session_interface_test_server_fixed 48/104 Test #48: session_interface_test_server_fixed ..... Passed 9.83 sec Start 49: session_interface_test_both_renew 49/104 Test #49: session_interface_test_both_renew ....... Passed 10.10 sec Start 50: session_interface_test_both_browser 50/104 Test #50: session_interface_test_both_browser ..... Passed 9.74 sec Start 51: session_interface_test_both_fixed 51/104 Test #51: session_interface_test_both_fixed ....... Passed 9.78 sec Start 52: proto_test_async_http 52/104 Test #52: proto_test_async_http ................... Passed 4.26 sec Start 53: proto_test_async_scgi 53/104 Test #53: proto_test_async_scgi ................... Passed 3.57 sec Start 54: proto_test_async_fastcgi 54/104 Test #54: proto_test_async_fastcgi ................ Passed 9.85 sec Start 55: proto_test_async_scgi_unix 55/104 Test #55: proto_test_async_scgi_unix .............. Passed 3.45 sec Start 56: proto_test_async_fastcgi_unix 56/104 Test #56: proto_test_async_fastcgi_unix ........... Passed 9.31 sec Start 57: proto_test_sync_http 57/104 Test #57: proto_test_sync_http .................... Passed 3.89 sec Start 58: proto_test_sync_scgi 58/104 Test #58: proto_test_sync_scgi .................... Passed 3.61 sec Start 59: proto_test_sync_fastcgi 59/104 Test #59: proto_test_sync_fastcgi ................. Passed 10.35 sec Start 60: proto_test_sync_scgi_unix 60/104 Test #60: proto_test_sync_scgi_unix ............... Passed 3.42 sec Start 61: proto_test_sync_fastcgi_unix 61/104 Test #61: proto_test_sync_fastcgi_unix ............ Passed 9.83 sec Start 62: proto_test_nonblocking_http 62/104 Test #62: proto_test_nonblocking_http ............. Passed 3.87 sec Start 63: proto_test_nonblocking_scgi 63/104 Test #63: proto_test_nonblocking_scgi ............. Passed 4.13 sec Start 64: proto_test_nonblocking_fastcgi 64/104 Test #64: proto_test_nonblocking_fastcgi .......... Passed 9.84 sec Start 65: proto_test_nonblocking_scgi_unix 65/104 Test #65: proto_test_nonblocking_scgi_unix ........ Passed 3.79 sec Start 66: proto_test_nonblocking_fastcgi_unix 66/104 Test #66: proto_test_nonblocking_fastcgi_unix ..... Passed 9.35 sec Start 67: test_function_function 67/104 Test #67: test_function_function .................. Passed 0.06 sec Start 68: test_function_callback 68/104 Test #68: test_function_callback .................. Passed 0.05 sec Start 69: test_ptime_posix_time 69/104 Test #69: test_ptime_posix_time ................... Passed 0.31 sec Start 70: test_thread_thread 70/104 Test #70: test_thread_thread ...................... Passed 3.84 sec Start 71: test_thread_fork 71/104 Test #71: test_thread_fork ........................ Passed 1.07 sec Start 72: test_smart_ptr_shared_ptr 72/104 Test #72: test_smart_ptr_shared_ptr ............... Passed 0.06 sec Start 73: test_smart_ptr_atomic_counter 73/104 Test #73: test_smart_ptr_atomic_counter ........... Passed 0.37 sec Start 74: test_smart_ptr_sp_counter 74/104 Test #74: test_smart_ptr_sp_counter ............... Passed 0.06 sec Start 75: test_log_log 75/104 Test #75: test_log_log ............................ Passed 0.06 sec Start 76: test_nowide_nowide 76/104 Test #76: test_nowide_nowide ...................... Passed 0.07 sec Start 77: test_iostreams_streambuf 77/104 Test #77: test_iostreams_streambuf ................ Passed 0.06 sec Start 78: test_regex_regex 78/104 Test #78: test_regex_regex ........................ Passed 0.07 sec Start 79: test_aio_reactor 79/104 Test #79: test_aio_reactor ........................ Passed 0.66 sec Start 80: test_aio_timer 80/104 Test #80: test_aio_timer .......................... Passed 0.26 sec Start 81: test_aio_event_loop 81/104 Test #81: test_aio_event_loop ..................... Passed 0.46 sec Start 82: test_aio_socket 82/104 Test #82: test_aio_socket ......................... Passed 1.19 sec Start 83: test_aio_endpoint 83/104 Test #83: test_aio_endpoint ....................... Passed 0.07 sec Start 84: test_backtrace_backtrace 84/104 Test #84: test_backtrace_backtrace ................ Passed 0.06 sec Start 85: test_aio_prefork 85/104 Test #85: test_aio_prefork ........................ Passed 0.58 sec Start 86: test_locale_codepage 86/104 Test #86: test_locale_codepage .................... Passed 1.69 sec Start 87: test_locale_message 87/104 Test #87: test_locale_message ..................... Passed 0.80 sec Start 88: test_locale_ios_prop 88/104 Test #88: test_locale_ios_prop .................... Passed 0.06 sec Start 89: test_locale_codepage_converter 89/104 Test #89: test_locale_codepage_converter .......... Passed 0.09 sec Start 90: test_locale_date_time 90/104 Test #90: test_locale_date_time ................... Passed 0.60 sec Start 91: test_locale_generator 91/104 Test #91: test_locale_generator ................... Passed 0.65 sec Start 92: test_locale_config 92/104 Test #92: test_locale_config ...................... Passed 0.42 sec Start 93: test_locale_utf 93/104 Test #93: test_locale_utf ......................... Passed 0.04 sec Start 94: test_locale_collate 94/104 Test #94: test_locale_collate ..................... Passed 1.03 sec Start 95: test_locale_convert 95/104 Test #95: test_locale_convert ..................... Passed 1.22 sec Start 96: test_locale_boundary 96/104 Test #96: test_locale_boundary .................... Passed 2.08 sec Start 97: test_locale_formatting 97/104 Test #97: test_locale_formatting .................. Passed 1.71 sec Start 98: test_locale_icu_vs_os_timezone 98/104 Test #98: test_locale_icu_vs_os_timezone .......... Passed 0.45 sec Start 99: test_locale_std_convert 99/104 Test #99: test_locale_std_convert ................. Passed 0.12 sec Start 100: test_locale_std_formatting 100/104 Test #100: test_locale_std_formatting .............. Passed 0.11 sec Start 101: test_locale_std_collate 101/104 Test #101: test_locale_std_collate ................. Passed 0.11 sec Start 102: test_locale_posix_collate 102/104 Test #102: test_locale_posix_collate ............... Passed 0.10 sec Start 103: test_locale_posix_convert 103/104 Test #103: test_locale_posix_convert ............... Passed 0.09 sec Start 104: test_locale_posix_formatting 104/104 Test #104: test_locale_posix_formatting ............ Passed 0.10 sec 100% tests passed, 0 tests failed out of 104 Total Test time (real) = 485.36 sec


-----Original Message-----
