### ISSUE TITLE
cppdb on github

### ISSUE THREAD

**Issue by alexbodn** [artyom-beilis/cppcms#71]
hello artyum,

thank you very much for providing your wonderful software. i would dare to try it too.

after testing cppdb from sourceforge, i found cppcms has a newer home here.

there are a few bug reports and pull requests for cppdb in cppcms issues, but you haven't created a repository for it here.
be so kind and do create a github repo for cppdb, so that it could get updates.

thanhs in advance,
alex

**Comment by dreaming-augustin** [comment]
For reference, here is the original source code for cppdb:
https://sourceforge.net/p/cppcms/code/HEAD/tree/cppdb/

I found at least one copy of it here at github:
https://github.com/melpon/cppdb 

The last commit appears to be 8 years old. So far nobody has volunteered to maintain the project.

I posted a critical patch without which cppdb does not work with MySQL 8.0:
https://github.com/artyom-beilis/cppcms/issues/70 
and I am about to share another patch for a feature that I had wanted for a long time.

All this to say that I am not competent enough, nor have I the time to volunteer to maintain the project, but I am still an active user of cppdb, and I will keep using this cppcms project here to file issues and share patches, unless someone maintains a repository elsewhere and accepts contributions.

**Comment by dreaming-augustin** [comment]
The label "cppdb" does not appear to exist in this github project, nor apparently would regular contributors be able to add that label, so "cppdb" should clearly be referenced in the title of relevant issues, at least until cppdb finds a more appropriate home.

**Comment by dreaming-augustin** [comment]
Oh! I see you have your own repository! :) including my MySQL 8.0 patch. 
https://github.com/alexbodn/cppdb 
Cool!

**Comment by dreaming-augustin** [comment]
The new official cppdb repository has just been created here: 
https://github.com/artyom-beilis/cppdb

**Comment by alexbodn** [comment]
thank you augustin and artium,

i am highly impressed of you taking cxx in the world of spoiled scripting
programmers, that i lately joined too.

i wish you good health and best of luck!
alex

**Comment by dreaming-augustin** [comment]
Thank you @alexbodn  and you're welcome! :smile:
