### ISSUE TITLE
Is it possible to use Https protocol with Cppcms?

### ISSUE THREAD

**Issue by suvidh** [artyom-beilis/cppcms#79]
If so how?
I think websites made with cppcms are HTTP and browsers register that as not secure... I want my website to use HTTPS.. taking a guess we are required to use OpenSSL but how to go about it?
consider me right in between a total noob and intermediate.

**Comment by artyom-beilis** [comment]
You can always use cppcms with existing high performance web server/reverse proxy like nginx and communicate with it using one of the supported protocols like FastCGI, SCGI or even HTTP. The web server will provide all SSL/https support.

In fact it is **the recommended** configuration - running behind http server.

The support of https/ssl is on the road map but there are higher priority features need to be implemented.

http://cppcms.com/wikipp/en/page/cppcms_1x_tasks#HTTP.Server.improvements
