### ISSUE TITLE
Can not build in VCStudio 2019

### ISSUE THREAD

**Issue by officefish** [artyom-beilis/cppcms#82]
Issue Log:
1>------ Сборка начата: проект: boost_locale, Конфигурация: Debug x64 ------
1>codepage.cpp
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(118,61): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(122,11): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(122,56): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(137,57): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(140,52): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(367,40): warning C4244: аргумент: преобразование "__int64" в "unsigned int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(361): message : во время компиляции функции-члена класс шаблон "std::string boost::locale::conv::impl::wconv_from_utf<CharType,2>::convert(const CharType *,const CharType *)"
1>        with
1>        [
1>            CharType=wchar_t
1>        ]
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\codepage.cpp(106): message : выполняется компиляция ссылки на экземпляр класс шаблон функции "boost::locale::conv::impl::wconv_from_utf<CharType,2>"
1>        with
1>        [
1>            CharType=wchar_t
1>        ]
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\codepage.cpp(161): message : выполняется компиляция ссылки на экземпляр шаблон функции "std::string boost::locale::conv::impl::convert_from<wchar_t>(const CharType *,const CharType *,const char *,boost::locale::conv::method_type)"
1>        with
1>        [
1>            CharType=wchar_t
1>        ]
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\encoding\wconv_codepage.ipp(376,50): warning C4244: аргумент: преобразование "__int64" в "unsigned int", возможна потеря данных
1>date_time.cpp
1>format.cpp
1>formatting.cpp
1>generator.cpp
1>ids.cpp
1>localization_backend.cpp
1>message.cpp
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\message.cpp(495,30): error C2976: std::map: слишком мало аргументов шаблон
1>D:\boost\boost_1_68_0\boost/detail/container_fwd.hpp(136): message : см. объявление "std::map"
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\message.cpp(744): message : выполняется компиляция ссылки на экземпляр класс шаблон функции "boost::locale::gnu_gettext::mo_message<CharType>"
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\message.cpp(739,34): error C2079: "boost::locale::gnu_gettext::mo_message<char>::domains_" использует не имеющую определения структуру class "std::map"
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\message.cpp(739,34): error C2079: "boost::locale::gnu_gettext::mo_message<wchar_t>::domains_" использует не имеющую определения структуру class "std::map"
1>mo_lambda.cpp
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\mo_lambda.cpp(286,88): warning C4244: =: преобразование "__int64" в "int", возможна потеря данных
1>info.cpp
1>locale_data.cpp
1>default_locale.cpp
1>codecvt_converter.cpp
1>codecvt.cpp
1>std_backend.cpp
1>win_backend.cpp
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(149,54): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(153,83): warning C4267: аргумент: преобразование из "size_t" в "int"; возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(153,53): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(170,83): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(170,74): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(245,46): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>D:\cppcms\boost_locale_4.0.0\libs\locale\src\win32\api.hpp(249,42): warning C4244: аргумент: преобразование "__int64" в "int", возможна потеря данных
1>gregorian.cpp
1>lcid.cpp
1>Создание кода...
1>Сборка проекта "boost_locale.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 0, с ошибками: 

This is error: D:\cppcms\boost_locale_4.0.0\libs\locale\src\shared\message.cpp(495,30): error C2976: std::map: слишком мало аргументов шаблон

**Comment by officefish** [comment]
Fixed it with ifdef statement

**Comment by artyom-beilis** [comment]
>  D:\cppcms\boost_locale_4.0.0

It isn't part of cppcms
