### ISSUE TITLE
Multiple processes, same port number

### ISSUE THREAD

**Issue by B1ackDrag0n** [artyom-beilis/cppcms#86]
Good morning.

Is it possible for multiple CppCMS processes, on a Linux machine, to share a port number, as discussed in this article?

[https://lwn.net/Articles/542629/](https://lwn.net/Articles/542629/), using "SO_REUSEPORT".

From the article:

> int sfd = socket(domain, socktype, 0);
> int optval = 1;
> setsockopt(sfd, SOL_SOCKET, SO_REUSEPORT, &optval, sizeof(optval));
> bind(sfd, (struct sockaddr *) &addr, addrlen);

Werner

**Comment by artyom-beilis** [comment]
No. This option isn't implemented but looks interesting indeed
