### ISSUE TITLE
Exception message: "No suck view" - typo

### ISSUE THREAD

**Issue by carbofos** [artyom-beilis/cppcms#89]
2021-12-17 07:52:28; cppcms, error: Caught exception [cppcms::view::pool: no suck view:render is registered for skin: baseskin]

Typo in error message

**Comment by artyom-beilis** [comment]
You need to provide little bit more information... For example what are you trying to do. Sample code, configuration, cppcms version, working environment etc.

**Comment by carbofos** [comment]
Oh, sorry.
The problem is incorrect message. I think the correct phrase should  be "no such view ... ".

**Comment by artyom-beilis** [comment]
Ahhh. ok

**Comment by dreaming-augustin** [comment]
Thank you @carbofos  for reporting.
