### ISSUE TITLE
Failing unittest

### ISSUE THREAD

**Issue by punkkeks** [artyom-beilis/cppcms#9]
> ./test_locale_formatting
>
> Testing char, UTF-8
> ----[1.31E1]!=
> ----[1.310E1] in 273
> Error in line:273 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[3:33:13 PM Greenwich Mean Time]!=
> ----[3:33:13 PM GMT] in 325
> Error in line:325 (ss.str())==(to_correct_string<CharType>("3:33:13 PM GMT",loc))
> ----[Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]!=
> ----[Thursday, February 5, 1970 at 3:33:13 PM GMT] in 366
> Error in line:366 (ss.str())==(to_correct_string<CharType>("Thursday, February 5, 1970" " at" " 3:33:13 PM GMT",loc))
> ----[Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]!=
> ----[Thursday, February 5, 1970 at 3:33:13 PM GMT] in 414
> Error in line:414 (ss.str())==(to_correct_string<CharType>(result[i],loc))
> ----[Greenwich Mean Time]!=
> ----[GMT] in 414
> Error in line:414 (ss.str())==(to_correct_string<CharType>(result[i],loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 ((booster::locale::basic_format<CharType>(fmt) % 13.1).str(loc))==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 ((booster::locale::basic_format<CharType>(fmt) % 13.1).str(loc))==(to_correct_string<CharType>("1.310E1",loc))
> Testing char, ISO8859-1
> ----[1.31E1]!=
> ----[1.310E1] in 273
> Error in line:273 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[3:33:13 PM Greenwich Mean Time]!=
> ----[3:33:13 PM GMT] in 325
> Error in line:325 (ss.str())==(to_correct_string<CharType>("3:33:13 PM GMT",loc))
> ----[Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]!=
> ----[Thursday, February 5, 1970 at 3:33:13 PM GMT] in 366
> Error in line:366 (ss.str())==(to_correct_string<CharType>("Thursday, February 5, 1970" " at" " 3:33:13 PM GMT",loc))
> ----[Thursday, February 5, 1970 at 3:33:13 PM Greenwich Mean Time]!=
> ----[Thursday, February 5, 1970 at 3:33:13 PM GMT] in 414
> Error in line:414 (ss.str())==(to_correct_string<CharType>(result[i],loc))
> ----[Greenwich Mean Time]!=
> ----[GMT] in 414
> Error in line:414 (ss.str())==(to_correct_string<CharType>(result[i],loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 448
> Error in line:448 ((booster::locale::basic_format<CharType>(fmt) % 13.1).str(loc))==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 (ss.str())==(to_correct_string<CharType>("1.310E1",loc))
> ----[1.31E1]!=
> ----[1.310E1] in 449
> Error in line:449 ((booster::locale::basic_format<CharType>(fmt) % 13.1).str(loc))==(to_correct_string<CharType>("1.310E1",loc))
> Failed Error limits reached, stopping unit test
>

**Comment by punkkeks** [comment]
Arch Linux, gcc 7.1.1

> locale
>
> LANG=en_US.UTF-8
> LC_CTYPE=de_DE.UTF-8
> LC_NUMERIC=de_DE.UTF-8
> LC_TIME=de_DE.UTF-8
> LC_COLLATE=de_DE.UTF-8
> LC_MONETARY=de_DE.UTF-8
> LC_MESSAGES=en_US.UTF-8
> LC_PAPER=de_DE.UTF-8
> LC_NAME=de_DE.UTF-8
> LC_ADDRESS=de_DE.UTF-8
> LC_TELEPHONE=de_DE.UTF-8
> LC_MEASUREMENT=de_DE.UTF-8
> LC_IDENTIFICATION=de_DE.UTF-8
> LC_ALL=
>

**Comment by artyom-beilis** [comment]
What ICU version do you have? in any case it isn't  something critical at all rather test issue

**Comment by punkkeks** [comment]
icu version 59.1-1

**Comment by artyom-beilis** [comment]
Issues with ICU 56 to 59 were found. Fixed in master.

**Comment by punkkeks** [comment]
Can you ref the commit please?

**Comment by artyom-beilis** [comment]
It is this one dbf94beaef0447caccea8410231919157195b6ab
However notice it is mostly import from Boost.Locale, original fix is there: https://github.com/boostorg/locale/commit/1bf387d96d151e8647f3483b695464167d5d74cd
